### ISSUE TITLE
Frontend

### ISSUE THREAD

**Issue by dawniemiec** [NiMiTZ-code/chargesnail#2]
@Erdevis do endpointów w axiosie musicie dodawać trailer slasha: -> nie 'api/alalala/alalal' tylko **/api/auth/users**
Problemy z brakiem połączenia wynikały z polityki CORS w przeglądarkach, w następnym obrazie powinno być dobrze. Generalnie, nie był to problem serwera.

Tak samo, metoda onSubmit => handle submit powinna znaleźć się w tagu form, a nie w buttonie, bo wtedy nie działa. 

Poprawić.

**Comment by MonMedrek** [comment]
Poprawione w login.jsx podobne błędy są w innych plikach.
